[General]
showlogo=hidden
showClock=true
# Replace with your own logo SVG path
logo=/usr/share/pixmaps/lyargoos-logo.svg
type=image
# LyargoOS accent color (logo blue)
color=#1793d1
fontSize=10
# Replace with your own wallpaper
background=/usr/share/wallpapers/LyargoOS-Dark/contents/images/7680x2160.jpg
needsFullUserModel=false
